config/routes.rb
Rails.application.routes.draw do
  get 'pages/media'
  devise_for :users
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  get "pages/media"
  get "posts/:id/download", to: "posts#download", as: "download_post"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
    has_one_attached :video

    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def media
    if user_signed_in?
      @posts = current_user.posts

      if @posts.empty?
        @message = "Wow, that's a clean portfolio"
      else
        @message = "Here's your portfolio: "
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  def download
    @post = Post.find(params[:id])
    send_data @post.video.download, filename: @post.video.filename.to_s
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy

    if @post.user_id == current_user.id
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :image, :video, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<div class="w-screen mt-12 py-16 bottom-0 left-0 bg-gray-500 overflow-hidden">
<footer class="m-8 flex justify-center">
 <p class="text-white text-center">This is the footer</p>
</footer>
</div>

app/views/layouts/_navbar.html.erb
<div class="bg-gray-200 py-4">
    <nav class="flex justify-between mx-5">
        <div>
            <span>MyTube Vids</span>
        </div>
        <div class="flex justify-evenly mx-11">
            <ul class="flex">
                <li><%= link_to "Home", root_path %></li>
                <% if current_user %>
                    <li class="mx-5"><a href="#"><%= link_to  "Upload", new_post_path %></a></li>
                    <li><%= link_to  "My Media", pages_media_path %></li>
                    <li class="mx-5"><%= button_to( "Log Out", destroy_user_session_path, method: :delete ) %></li>
                    <% else %>
                    <li><a href="#"><%=  link_to "Sign up", new_user_registration_path %></a></li>
                <% end %>
            </ul>
        </div>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Youtube</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div style="height: 100vh;">
      <%= render 'layouts/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="container px-5 mx-auto content mt-28 overscroll-y-auto">
         <%= yield %>
      </div>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/media.html.erb
<h6>
  <%= @message %>
</h6>

<%= link_to "Upload", new_post_path, class: "bg-black hover:bg-gray-500 text-white py-2 px-4 rounded inline-flex items-center" %>
<br>
<br>
<% if current_user %>
  <div id="posts">
    <%= render  @posts %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <div>
    <%= form.label :video, style: "display: block" %>
    <%= form.file_field :video %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>
  <div class="my-3">
    <button class="px-4 py-2 bg-green-500 text-white font-semibold rounded hover:bg-green-600">
      <%= form.submit %>
    </button>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="youtube-layout">
  <%# post.video.blob.metadata.fetch(:duration, nil) %>
  <% if post.image.attached? %>
    <%= image_tag(post.image, class: "thumbnail") %>
  <% end %>
  <% if action_name != "show" %>
    <%= link_to post, class: "overlay" do %>
      <div class="overlay-content">
        <h2 class="post-title"><%= post.title %></h2>
        <p class="text-white post-details">
          <%#= post.user.email %>
          <br>
          Posted <%= time_ago_in_words(post.created_at) %> ago
        </p>
      </div>
    <% end %>
  <% end %>
</div>
<style>
  .youtube-layout {
    position: relative;

    width: 24%;
    height: 200px;
    box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;
    display: inline-block;
    align-items: center; /* Center vertically */
    justify-content: center; /* Center horizontally */
  }

  .thumbnail {
    display: block;
    max-width: 100%;
    max-height: 100%;
    width: 100%; /* Fill the container width */
    height: 100%; /* Fill the container height */
    object-fit: cover; /* Maintain aspect ratio and fill the container */
  }

  .overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    color: white;
    background-color: rgba(0, 0, 0, 0.7);
    text-decoration: none;
    display: flex;
    align-items: center;
    justify-content: center;
    opacity: 0;
    transition: opacity 0.3s;
  }

  .overlay-content {
    text-align: center;
  }

  .overlay:hover {
    opacity: 1;
  }

  .overlay:hover .thumbnail {
    filter: brightness(70%);
  }

  .post-title {
    font-size: 18px;
    font-weight: bold;
    margin-bottom: 8px;
  }

  .post-details {
    font-size: 14px;
  }

  /* Responsive changes */
  @media screen and (max-width: 768px) {
    .youtube-layout {
      width: 100%;
    }
  }
</style>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="inline-block px-3 py-2 mb-5 font-medium text-green-500 rounded-lg bg-green-50" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex items-center justify-between">
    <%#= link_to 'New post', new_post_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div id="posts" class="min-w-full">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path, class: "px-4 py-2 bg-blue-500 text-white font-semibold rounded hover:bg-blue-600" %>
</div>

app/views/posts/show.html.erb
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<div class="youtube-layout">
  <% if @post.video.attached? %>
    <div class="video-container">
      <video controls>
        <source src="<%= url_for(@post.video) %>" type="video/mp4">
        Your browser does not support the video tag.
      </video>
    </div>
  <% else %>
    <% if @post.image.attached? %>
      <%= image_tag(@post.image, class: "thumbnail") %>
    <% end %>
  <% end %>
  <div class="overlay">
    <div class="overlay-content">
      <h2 class="text-lg post-details"><%= @post.title %></h2>
      <h2 class="text-lg post-details"><%#= @post.hits %> views </h2>
      <p class="post-details">
        <%= @post.user.email %>
        <br>
        <%= time_ago_in_words(@post.created_at) %> ago
      </p>
    </div>
  </div>
  <% if current_user %>
    <div>
      <%#= button_to "like", likes_path, params: {like: {post_id: @post.id}}, method: :post, class:"mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%#= @post.likes.count %>
    </div>
    <%if @post.user_id == current_user.id %>
      <%= link_to 'Edit', edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2 ">
        <%= button_to 'Delete', post_path(@post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
    <% end %>
  <% end %>
  <% if @post.video.attached? %>
    <%= link_to 'Download', download_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
  <% end %>
</div>
<style>
  .youtube-layout {
  margin: 0 auto;
  width: 60%;
  box-shadow: rgba(0, 0, 0, 0.2) 0px 0px 8px 0px;
  }

  .thumbnail {
   display: block;
   max-width: 100%;
   max-height: 100%;
   width: auto;
   height: auto;
   margin: 0 auto;
   object-fit: contain;
  }

  .post-details {
  padding: 10px;
  }

  .post-title {
  font-size: 24px;
  font-weight: bold;
  margin-bottom: 8px;
  }

  .post-details p {
  font-size: 14px;
  }      .video-container {
        position: relative;
        padding-bottom: 56.25%; /* 16:9 aspect ratio (change as needed) */
        padding-top: 30px;
        height: 0;
        overflow: hidden;
      }

      .video-container video {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
      }
</style>